name: Renovate

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 every day
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: info
